name = "Heuristic"
uuid = "9f686a04-418b-46e3-a7ce-cbf2c26242ec"
authors = ["Felipe <felipe.gallois@inf.ufrgs.br>", "Henrique <hugobbi@inf.ufrgs.br>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
